/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'TRANSLATORAI',systemName:'知华企业翻译智能体',englishName:'ENTERPRISE TRANSLATION AI',theme:{primary:'#3e6292',dark:'#223149',accent:'#c88b52'},
 workspace:'全球内容中心 / 语言运营组',fieldWorkspace:'产品文档组 / 中英译审',period:'2026-08-17 · 第 34 周',liveText:'术语库于 14:08 同步',fieldContextLabel:'当前语言对',fieldContext:'简体中文 → 英语',fieldUser:'苏禾',fieldRole:'译审专员',adminUser:'陆闻',adminRole:'语言平台主管',
 adminTitle:'企业翻译运营中心',adminBreadcrumb:'内容智能 / 翻译协作',adminSubtitle:'统一管理文档、术语、机翻置信度、人工译审与多语言发布证据。',exportAction:'导出语言质量报告',createAction:'新建翻译任务',chartTitle:'译文一次通过率',chartSubtitle:'实际通过率 / 质量目标',chartLabels:['W26','W27','W28','W29','W30','W31','W32','W33','W34'],loadTitle:'语言对任务负载',loadSubtitle:'待译字数与交付容量',recordsTitle:'重点翻译项目',recordsSubtitle:'按保密、法律风险和交付日期排序',issueTitle:'语言质量提醒',issueSubtitle:'低术语覆盖、低置信度和版式异常',
 recordName:'翻译任务',itemName:'文档 / 版本',unitName:'业务团队',batchName:'语言对',planName:'总段落',doneName:'已译审',exceptionName:'问题',unitLabel:'段',listBreadcrumb:'翻译协作 / 项目队列',listSubtitle:'源文、机器草稿、术语命中、人工修订和发布审批均可追溯。',listSummary:[['本周字数','286k'],['进行中','42'],['高风险','8',true],['已交付','31']],tabs:['全部','待预翻译','译审中','待批准','已发布'],
 fieldBreadcrumb:'译审工作台 / 产品文档',fieldTitle:'双语译审工作台',fieldSubtitle:'我的任务 7 个 · 待修订 18 段 · 今日交付 2 个',fieldSecondary:'打开双语对照',reportAction:'提交译审结果',fieldNoticeTitle:'术语与记忆库已加载',fieldNotice:'核心术语覆盖率 94.2%',steps:['文档解析','术语匹配','机器草稿','人工译审','发布确认'],documentAction:'查看源文档',printAction:'导出双语稿',resourceCardTitle:'语言资源',resourceValueLabel:'企业术语',resourceHealthLabel:'术语覆盖率',quickSubtitle:'译审工作入口',quickActions:[['继续译审','/shopfloor/report','双语段落与质量检查'],['文档资产','/shopfloor/material','源文、版本和附件'],['语言资源','/shopfloor/resources','术语库、记忆库和模型'],['风险升级','/shopfloor/andon','保密、法律和低置信度']],
 reportDefaults:[18,2],reportTitle:'译审结果反馈',reportSubtitle:'记录通过段落、问题段落和修订说明。',reportSuccess:'译审结果已提交',reportPlaceholder:'填写术语修订、语义偏差、格式问题或发布备注',reportFootnote:'法律与保密文档必须由高级译审确认',ruleTitle:'多语言发布门禁',ruleSubtitle:'LINGUA-GATE · V1.0',rules:[['核心术语','必须一致'],['数字单位','逐项核对'],['保密文档','仅私有化处理'],['法律条款','高级译审',true]],fieldTotals:[['7','我的任务'],['18','待修订段落'],['8,642','企业术语'],['94.2%','术语覆盖率']],
 adminMenus:[['/admin','home','翻译运营中心'],['/admin/work-orders','order','翻译项目'],['/admin/samples','box','文档资产'],['/admin/schedule','calendar','交付计划'],['/admin/methods','process','质量规则'],['/admin/reviews','quality','发布审批'],['/admin/resources','machine','语言资源'],['/admin/report','chart','语言分析']],fieldMenus:[['/shopfloor','home','译审工作台'],['/shopfloor/report','report','译审反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','文档资产'],['/shopfloor/resources','machine','语言资源'],['/shopfloor/andon','risk','风险升级',2]],moduleTitles:{tasks:['我的翻译任务','查看语言对、字数和交付日期'],material:['文档资产','统一管理源文、附件和版本'],resources:['语言资源中心','管理术语、记忆库和模型版本'],andon:['翻译风险升级','处理保密、法律和低置信度问题'],samples:['文档资产','维护模板与内容类型'],schedule:['交付计划','协调语言对和译审产能'],methods:['质量规则','维护术语、数字和格式检查'],reviews:['发布审批','记录通过、退回和修订要求'],report:['语言质量分析','分析通过率、术语和返工原因']},
 tagline:'让企业内容跨越语言，仍然准确可控',storyTitle:'机器先翻，人工把关，<br/>关键术语始终一致',storyText:'面向产品、合同和运营内容，提供私有化友好的翻译与译审协作流程。',pattern:[2,3,6,9,10,14,18,20,23,27,31,35],loginStats:[['286k','本周处理字数'],['94.2%','术语覆盖率'],['8','高风险文档']],loginTitle:'企业翻译运营中心',adminDemo:'项目 / 术语 / 质量',fieldDemo:'双语 / 译审 / 发布'}
export const records=[{no:'TR-260817-052',name:'智能网关安装手册 v3.2',code:'DOC-GW-032',unit:'工业产品组',group:'产品文档',plan:286,done:198,exception:12,due:'08-18',batch:'zh-CN → en-US',status:'译审中',progress:69,priority:'重点'},{no:'TR-260817-048',name:'欧洲经销协议 2026',code:'LEGAL-EU-26',unit:'国际法务组',group:'合同文件',plan:164,done:82,exception:9,due:'08-19',batch:'zh-CN → de-DE',status:'高级复核',progress:50,priority:'高风险'},{no:'TR-260817-043',name:'移动端更新说明',code:'APP-RN-826',unit:'数字产品组',group:'产品运营',plan:48,done:48,exception:1,due:'今天',batch:'zh-CN → ja-JP',status:'待批准',progress:100,priority:'正常'},{no:'TR-260816-036',name:'供应商质量规范',code:'SQM-GUIDE',unit:'供应链组',group:'质量文件',plan:126,done:126,exception:3,due:'08-16',batch:'zh-CN → en-US',status:'已发布',progress:100,priority:'重点'},{no:'TR-260815-029',name:'官网解决方案页面',code:'WEB-SOLUTION',unit:'品牌市场组',group:'市场内容',plan:72,done:72,exception:0,due:'08-15',batch:'zh-CN → en-US',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'TERM-CORE',name:'企业核心术语库',unit:'语言运营组',status:'运行中',health:98,value:'8,642',valueUnit:'词',note:'本周新增 126 个审核术语'},{code:'TM-PRODUCT',name:'产品翻译记忆库',unit:'产品文档组',status:'运行中',health:96,value:'186k',valueUnit:'句对',note:'重复内容命中率 41.8%'},{code:'MODEL-PRIVATE',name:'私有翻译模型',unit:'智能内容组',status:'复核中',health:94,value:'v3.4',valueUnit:'',note:'法律语料评测等待确认'}]
export const reviews=[{no:'LR-260817-032',title:'欧洲经销协议',type:'高级译审',detail:'法律条款 28 段 · 陆闻',result:'待确认'},{no:'LR-260817-027',title:'移动端更新说明',type:'发布审批',detail:'术语覆盖 98.6% · 苏禾',result:'通过'},{no:'LR-260817-018',title:'智能网关安装手册',type:'质量复核',detail:'12 段低于置信阈值',result:'异常'}]
export const adminMetrics=[['本周处理','286k 字','覆盖 12 个语言对','blue'],['一次通过率','91.6%','较上周提升 2.1%','green'],['待高级译审','8 份','5 份为法律文件','orange'],['临期任务','3 份','均已分配译审人','red']]
export const fieldMetrics=[['我的任务','7 份','2 份今日交付','blue'],['今日已译审','428 段','一次通过 93.2%','green'],['待修订','18 段','主要为术语问题','orange'],['术语覆盖率','94.2%','高于团队目标','slate']]
export const chartActual=[82,84,85,87,86,88,89,90,92],chartTarget=[86,86,87,87,88,89,90,90,92]
export const loads=[['中英产品文档',82,'待译 86k 字'],['中德法律文件',74,'待译 42k 字'],['中日产品运营',58,'待译 26k 字'],['多语言市场内容',43,'待译 18k 字']]
export const issues=[['法律','经销协议包含责任限制条款','已安排高级译审逐句对照','待批准'],['术语','网关手册出现 12 个未审术语','已提交产品团队确认','处理中'],['格式','日语更新说明列表编号错位','已自动修复并等待预览','待确认']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
